### ISSUE TITLE
makiki docs not building from .texi for me

### ISSUE THREAD

**Issue by reuleaux** [shirok/Gauche-makiki#8]
I have successfully installed _makiki_, thank you so much!

with these steps roughly:
```
cd ~/tmp
git clone https://github.com/shirok/Gauche-makiki
cd Gauche-makiki
./configure --prefix=/home/rx/opt/gauche
make install
```
my gauche installation being in ~/opt/gauche, now I can in gosh just
```
(use makiki)
```
so far so good, i.e. I am ready to go, and learn more.

Now I am trying to build the docs from the `.texi`

```
cd doc
```
and a `Makefile` has already been created there, as a result of the the above
`make configure `step. Thus I try `make`, which results in an error however.
```
rx@softland {master} ~/tmp/Gauche-makiki/doc $ make
"/home/rx/opt/gauche/bin/gosh" tools/preprocess-info -en -o gauche-makiki.en.texi gauche-makiki.texi
*** ERROR: cannot find "tools/preprocess-info" in ("/home/rx/opt/gauche/share/gauche-0.98/site/lib" "/home/rx/opt/gauche/share/gauche-0.98/0.9.14/lib")
Stack Trace:
_______________________________________
  0  (find-load-file file paths suffixes :error-if-not-found error ...
make: *** [Makefile:42: gauche-makiki.en.texi] Error 70
```
Any advice? Thanks.
-Andreas

**Comment by shirok** [comment]
Thanks for reporting it.  We changed the script name right before 0.9.14 release, but forgot to update this one.

**Comment by shirok** [comment]
btw, the info file is mostly empty now.  The plan is to move the detailed description in README to info.

**Comment by reuleaux** [comment]
OK, thanks.
